version: '3.8'
services:

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "8081:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      #- "443:443/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
    environment:
      # Set the appropriate timezone for your location from
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones, e.g:
      TZ: 'Europe/London'
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: '[redacted]'
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: 'all'
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - './etc-pihole:/etc/pihole'
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - "./mosquitto-data:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
        max-file: "3"
        max-size: "10m"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
        max-file: "3"
        max-size: "10m"

  # watching images for updates
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      WATCHTOWER_NOTIFICATIONS: 'email'
      WATCHTOWER_NOTIFICATION_REPORT: 'true'
      WATCHTOWER_NOTIFICATION_TITLE_TAG: 'zigbee2mqtt-pi'
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: 'watchtower@mg.shoogland.com'
      WATCHTOWER_NOTIFICATION_EMAIL_TO: 'stephan@shoogland.com'
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: 'smtp.mailgun.org'
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: '587'
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: 'watchtower@mg.shoogland.com'
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: '[redacted]'
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: '2'
    command: --schedule "0 0 2 * * SUN" --cleanup
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
        max-file: "3"
        max-size: "10m"
    restart: unless-stopped

  nginx-proxy:
    image: nginx:1.29.3
    expose:
      - "80"
    volumes:
      - ./nginx-config/proxy.conf:/etc/nginx/conf.d/default.conf
    labels:
      - traefik.enable=true
      - "traefik.http.middlewares.forward-auth.forwardauth.address=https://auth.shoogland.com/auth"
      - "traefik.http.routers.stationsweg-shoogland-com-http.rule=Host(`stationsweg.shoogland.com`)"
      - "traefik.http.routers.stationsweg-shoogland-com-http.entrypoints=web"
      - "traefik.http.routers.stationsweg-shoogland-com-https.rule=Host(`stationsweg.shoogland.com`)"
      - "traefik.http.routers.stationsweg-shoogland-com-https.entrypoints=websecure"
      - "traefik.http.routers.stationsweg-shoogland-com-https.tls=true"
      - "traefik.http.routers.stationsweg-shoogland-com-https.tls.certresolver=myresolver"
      - "traefik.http.routers.p1monitor-shoogland-com-http.entrypoints=web"
      - "traefik.http.routers.p1monitor-shoogland-com-https.rule=Host(`p1monitor.shoogland.com`)"
      - "traefik.http.routers.p1monitor-shoogland-com-https.entrypoints=websecure"
      - "traefik.http.routers.p1monitor-shoogland-com-https.tls=true"
      - "traefik.http.routers.p1monitor-shoogland-com-https.tls.certresolver=myresolver"
      - "traefik.http.routers.p1monitor-shoogland-com-http.middlewares=forward-auth"
      - "traefik.http.routers.p1monitor-shoogland-com-https.middlewares=forward-auth"
      - "traefik.http.routers.octoprint-shoogland-com-http.rule=Host(`octoprint.shoogland.com`)"
      - "traefik.http.routers.octoprint-shoogland-com-http.entrypoints=web"
      - "traefik.http.routers.octoprint-shoogland-com-https.rule=Host(`octoprint.shoogland.com`)"
      - "traefik.http.routers.octoprint-shoogland-com-https.entrypoints=websecure"
      - "traefik.http.routers.octoprint-shoogland-com-https.tls=true"
      - "traefik.http.routers.octoprint-shoogland-com-https.tls.certresolver=myresolver"
      - "traefik.http.routers.octoprint-shoogland-com-http.middlewares=forward-auth"
      - "traefik.http.routers.octoprint-shoogland-com-https.middlewares=forward-auth"
      - "traefik.http.routers.scouting-shoogland-com-http.rule=Host(`scouting.shoogland.com`)"
      - "traefik.http.routers.scouting-shoogland-com-http.entrypoints=web"
      - "traefik.http.routers.scouting-shoogland-com-https.rule=Host(`scouting.shoogland.com`)"
      - "traefik.http.routers.scouting-shoogland-com-https.entrypoints=websecure"
      - "traefik.http.routers.scouting-shoogland-com-https.tls=true"
      - "traefik.http.routers.scouting-shoogland-com-https.tls.certresolver=myresolver"
      - "traefik.http.routers.scouting-shoogland-com-http.middlewares=forward-auth"
      - "traefik.http.routers.scouting-shoogland-com-https.middlewares=forward-auth"
      - "traefik.http.routers.pihole-shoogland-com-http.rule=Host(`pihole.shoogland.com`)"
      - "traefik.http.routers.pihole-shoogland-com-http.entrypoints=web"
      - "traefik.http.routers.pihole-shoogland-com-https.rule=Host(`pihole.shoogland.com`)"
      - "traefik.http.routers.pihole-shoogland-com-https.entrypoints=websecure"
      - "traefik.http.routers.pihole-shoogland-com-https.tls=true"
      - "traefik.http.routers.pihole-shoogland-com-https.tls.certresolver=myresolver"
      - "traefik.http.routers.pihole-shoogland-com-http.middlewares=forward-auth"
      - "traefik.http.routers.pihole-shoogland-com-https.middlewares=forward-auth"
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
        max-file: "3"
        max-size: "10m"
    restart: unless-stopped

  # webproxy traefik
  traefik:
    image: traefik:v3.5
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=stephan@shoogland.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
        max-file: "3"
        max-size: "10m"
    restart: unless-stopped
